In [1]:
pip install opencv-python

In [2]:
pip install opencv--upgrade

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement opencv--upgrade (from versions: none)
ERROR: No matching distribution found for opencv--upgrade


In [3]:
import cv2
cv2.__version__

'4.9.0'

In [4]:
import numpy as np
import pandas as pd

### Load/Read Image

In [5]:
# Load an image using 'imread' specifying the path to image
img=cv2.imread('image_examples/Modi.jpg',0)    #1-Color,  0-B/W
  


In [6]:
# Display the image
cv2.imshow('Modi',img)  #Modi---name on the display
cv2.waitKey()    ##Means waits until we close,we can give time also in brackets
cv2.destroyAllWindows()

### Let's take a closer look at how images are stored

In [7]:
##prints pixels of the image   B/W -->2D, Colour-->3D
print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [8]:
type(img)

numpy.ndarray

In [9]:
img.ndim

2

In [10]:
img.shape

(1358, 1500)

In [11]:
pwd

'C:\\Users\\Mitta Aasish Kumar\\Data Science Course\\Artificial Intelligence\\Computer Vision'

## Resize Image

In [12]:
img=cv2.imread(r'C:\Users\Mitta Aasish Kumar\Data Science Course\Artificial Intelligence\Computer Vision\image_examples\Modi.jpg',1)

resized_image=cv2.resize(img,(750,679))  #resizing to 50%,Color Image

gray=cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY) #B & W

cv2.imshow('Modi Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

## Save Image

In [13]:
##Saves in same directory
cv2.imwrite('pm_resize.jpg',resized_image)

True

## Face Detection using HAAR Cascade Classifiers

In [14]:
#Load the face features
face_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

#Load the image
image=cv2.imread(r'C:\Users\Mitta Aasish Kumar\Data Science Course\Artificial Intelligence\Computer Vision\image_examples\Modi.jpg',1)

resized_image=cv2.resize(image,(679,750))

gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.05,5)   #Image tuning

print(faces)

[[276 128 301 301]]


- For increasing accuracy reduce zoom size

In [16]:
face_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
image=cv2.imread(r'C:\Users\Mitta Aasish Kumar\Data Science Course\Artificial Intelligence\Computer Vision\image_examples\Modi.jpg',1)

image=cv2.resize(image,(679,750))

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.01,5)

if faces is ():
    print("No faces found")
else:
    for(x,y,l,b) in faces:
        cv2.rectangle(image, (x,y), (x+1,y+b), (0,255,0),1)
        
cv2.imshow('Face Detection',image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Mitta Aasish Kumar\AppData\Local\Temp\ipykernel_21668\1128125491.py:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Face & Eye detectionusing HAAR Cascade Classifiers in Image

In [17]:
import numpy as np

In [19]:
face_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

eye_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

img=cv2.imread(r'C:\Users\Mitta Aasish Kumar\Data Science Course\Artificial Intelligence\Computer Vision\image_examples\Modi.jpg',1)

resized_image=cv2.resize(image,(500,500))

gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.03,5)

if faces is ():
    print("No faces found")
    
for(x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resized_image[y:y+h,x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),1)
        
cv2.imshow('img',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Mitta Aasish Kumar\AppData\Local\Temp\ipykernel_21668\3304464233.py:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Capture a Video

In [20]:
#Doing some face recognisation with the webcam

import cv2
video=cv2.VideoCapture(0)   #0-webcam

while True:
    num,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',frame)
    if cv2.waitKey(1)==ord('q'):   # if we click q then only video closes
        break

video.release()
cv2.destroyAllWindows()

## Face & Eye Detection using HAAR Cascade Classifiers

In [21]:
face_cascade=cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

eye_cascade=cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

def detect(gray,frame):
    faces=face_cascade.detectMultiScale(gray,1.05,5)
    for(x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=resized_image[y:y+h,x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray,1.05,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

#Doing some face recognisation with the webcam
video=cv2.VideoCapture(0)

while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas=detect(gray,frame)
    cv2.imshow('Video',canvas)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

## Pedistrian Detection

In [22]:
import cv2

#Create our body classifier
body_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_fullbody.xml')

#Initiate video capture for video file
cap=cv2.VideoCapture('image_examples\walking.avi')

while cap.isOpened():
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies=body_classifier.detectMultiScale(gray,1.2,4) #Zoom
    #(filename,zoom,no.of nearest neighbors)
    
    #Extract bounding boxes for any bodies identified
    for (x,y,w,h)in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        #That shows rectangle on image in each frame of the video
        cv2.imshow('Pedestrians',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [24]:
import time

#Create our body classifier
car_classifier=cv2.CascadeClassifier('Haarcascades/haarcascade_car.xml')

#Initiate video capture for video file
cap=cv2.VideoCapture('image_examples\car.avi')

#Loop once video is successfully loaded
while cap.isOpened():
    time.sleep(.01)
    #Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cars=car_classifier.detectMultiScale(gray,1.4,2)
    
    #Extract bounding boxes for any bodies identified
    for(x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Cars',frame)
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()